# SuGaR build/run environment — source this before building extensions or running the pipeline.
#   source /home/acer/workspace/dirac/SuGaR/env.sh

# Prefer the machine-specific profile generated by scripts/setup_wizard.sh.
# SUGARRUSH_SETUP_ENV can point at a non-default profile for controlled builds.
SUGARRUSH_ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUGARRUSH_GENERATED_ENV="${SUGARRUSH_SETUP_ENV:-$SUGARRUSH_ENV_DIR/.setup/runtime.env}"
if [[ -f "$SUGARRUSH_GENERATED_ENV" ]]; then
  # shellcheck disable=SC1090
  source "$SUGARRUSH_GENERATED_ENV"
  unset SUGARRUSH_ENV_DIR SUGARRUSH_GENERATED_ENV
  return 0 2>/dev/null || exit 0
fi
unset SUGARRUSH_ENV_DIR SUGARRUSH_GENERATED_ENV

# --- CUDA 11.8 toolkit (toolkit only; the Windows driver provides the GPU under WSL2) ---
export CUDA_HOME=/usr/local/cuda-11.8
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

# --- CUDA 11.8 supports gcc <= 11, Ubuntu 24.04 defaults to gcc-13 ---
export CC=/usr/bin/gcc-11
export CXX=/usr/bin/g++-11
export NVCC_PREPEND_FLAGS='-ccbin /usr/bin/g++-11'

# --- GPU architecture. GTX 1650 is Turing = compute capability 7.5.
# +PTX embeds forward-compatible PTX so the binary still JITs on a newer card.
# NOTE: the runbook's "8.9" is for RTX 40xx and produces binaries that CANNOT
# run here; the failure surfaces as a bogus "out of memory" from simple-knn.
export TORCH_CUDA_ARCH_LIST="7.5+PTX"

# --- Build parallelism. This box has 7.7 GB RAM / 2 GB swap; nvcc peaks around
# 2-3 GB per translation unit, so the default (nproc=8) OOMs the machine. ---
export MAX_JOBS=2
